#docker build --no-cache --build-arg IMAGE_VERSION=latest --file Dockerfile.alpine --tag image-name:version .
#xhost +local:docker
#docker run --interactive --tty --volume /tmp/.X11-unix:/tmp/.X11-unix --env DISPLAY=unix$DISPLAY --name container-name image-name:version
